namespace System.Speech.Internal.SapiInterop
{
	internal enum SPINTERFERENCE
	{
		SPINTERFERENCE_NONE,
		SPINTERFERENCE_NOISE,
		SPINTERFERENCE_NOSIGNAL,
		SPINTERFERENCE_TOOLOUD,
		SPINTERFERENCE_TOOQUIET,
		SPINTERFERENCE_TOOFAST,
		SPINTERFERENCE_TOOSLOW
	}
}
